#ifndef PARSER_INTERNAL_H
#define PARSER_INTERNAL_H

#include "parser/ast.h"
#include "parser/parser.h"

struct ColParser
{
    apr_pool_t *pool;
    void *yyscanner;
    AstProgram *result;
};

/* Generated by Bison from ol_parse.y */
int yyparse();

/* ol_scan.l */
char *setup_scan_buf(const char *str, apr_size_t len, apr_pool_t *pool);

#endif  /* PARSER_INTERNAL_H */
