#ifndef PARSER_INTERNAL_H
#define PARSER_INTERNAL_H

#include "parser/ast.h"
#include "parser/parser.h"
#include "util/strbuf.h"

typedef struct C4Parser
{
    apr_pool_t *pool;
    void *yyscanner;
    AstProgram *result;

    /* Contents of the currently-being-lexed string literal */
    StrBuf *lit_buf;
} C4Parser;

/* Generated by Bison from ol_parse.y */
int yyparse(C4Parser *context, void *scanner);

/* ol_scan.l */
char *setup_scan_buf(const char *str, apr_size_t len, apr_pool_t *pool);

#endif  /* PARSER_INTERNAL_H */
