#include "col-internal.h"

#include "ol_scan.h"
#include "parser/parser.h"

/* Generated by Bison from ol_parse.y */
extern int yyparse();

struct ColParser
{
    int foo;
};

ColParser *
parser_init(ColInstance *col)
{
    ColParser *result = ol_alloc(sizeof(*result));
    return result;
}

AstProgram *
parser_do_parse(ColParser *parser, const char *src)
{
    int result;
    YY_BUFFER_STATE scanbuf;

    /* Setup buffer for flex */
    scanbuf = yy_scan_string(src);

    result = yyparse();
    if (result)
    {
        yy_delete_buffer(scanbuf);
        return NULL;
    }

    yy_delete_buffer(scanbuf);
    return NULL;
}

ColStatus
parser_destroy(ColParser *parser)
{
    ol_free(parser);
    return COL_OK;
}
