#include "col-internal.h"

#include "ol_scan.h"
#include "parser/parser.h"

/* Generated by Bison from ol_parse.y */
extern int yyparse();

/* Defined in ol_scan.l */
extern char *setup_scan_buf(const char *str, apr_size_t len, apr_pool_t *pool);

struct ColParser
{
    apr_pool_t *pool;
};

ColParser *
parser_make(ColInstance *col)
{
    apr_pool_t *pool;
    ColParser *parser;

    pool = make_subpool(col->pool);
    parser = apr_palloc(pool, sizeof(*parser));
    parser->pool = pool;
    return parser;
}

AstProgram *
parser_do_parse(ColParser *parser, const char *str)
{
    apr_size_t slen;
    char *scan_buf;
    YY_BUFFER_STATE buf_state;
    int parse_result;

    slen = strlen(str);
    scan_buf = setup_scan_buf(str, slen, parser->pool);
    buf_state = yy_scan_buffer(scan_buf, slen + 2);

    parse_result = yyparse();
    if (parse_result)
    {
        yy_delete_buffer(buf_state);
        return NULL;
    }

    yy_delete_buffer(buf_state);
    return NULL;
}

ColStatus
parser_destroy(ColParser *parser)
{
    apr_pool_destroy(parser->pool);
    return COL_OK;
}
