#include "col-internal.h"

#include "ol_scan.h"
#include "parser/parser.h"

/* Generated by Bison from ol_parse.y */
extern int yyparse();

struct ColParser
{
    apr_pool_t *pool;
};

ColParser *
parser_make(ColInstance *col)
{
    apr_pool_t *pool;
    ColParser *parser;

    pool = make_subpool(col->pool);
    parser = apr_palloc(pool, sizeof(*parser));
    parser->pool = pool;
    return parser;
}

AstProgram *
parser_do_parse(ColParser *parser, const char *str)
{
    size_t slen;
    char *scan_buf;
    YY_BUFFER_STATE buf_state;
    int parse_result;

    /* XXX: temp hack */
#define YY_END_OF_BUFFER_CHAR '\0'

    /* Setup scan buffer, with special termination needed by Flex */
    slen = strlen(str);
    scan_buf = apr_palloc(parser->pool, slen + 2);
    memcpy(scan_buf, str, slen);
	scan_buf[slen] = scan_buf[slen + 1] = YY_END_OF_BUFFER_CHAR;
    buf_state = yy_scan_buffer(scan_buf, slen + 2);

    parse_result = yyparse();
    if (parse_result)
    {
        yy_delete_buffer(buf_state);
        return NULL;
    }

    yy_delete_buffer(buf_state);
    return NULL;
}

ColStatus
parser_destroy(ColParser *parser)
{
    apr_pool_destroy(parser->pool);
    return COL_OK;
}
